import { createDefaultAccountState } from "../services/account-service.js";
import { createSpotifySessionState } from "../integrations/spotify-service.js";
import { createDefaultNearbyState } from "../services/nearby-detection-service.js";
import { cloneData } from "../utils/formatters.js";

export function createDefaultState() {
  const seeded = createDefaultAccountState();
  const activeWorkspace = seeded.accountVault[seeded.previewAccountId];
  const currentAccount = seeded.accounts.find((account) => account.id === seeded.previewAccountId);

  return {
    version: 3,
    currentUser: {
      id: currentAccount.id,
      name: currentAccount.name,
      displayName: currentAccount.displayName,
      username: currentAccount.username,
      profileId: currentAccount.profileId,
      avatarLabel: currentAccount.avatarLabel,
      avatar: currentAccount.avatarLabel,
      avatarUrl: currentAccount.avatarUrl || "",
      email: currentAccount.email,
      provider: currentAccount.provider,
      providerType: currentAccount.provider,
      homeCourse: currentAccount.homeCourse,
      handicap: currentAccount.handicap,
      handedness: currentAccount.handedness || "",
      bio: currentAccount.bio,
      seasonGoal: currentAccount.seasonGoal,
      city: currentAccount.city,
      createdAt: currentAccount.createdAt,
      premiumStatus: currentAccount.subscription.tier,
      privacy: cloneData(currentAccount.privacy),
      appearance: cloneData(currentAccount.appearance),
      social: cloneData(currentAccount.social),
      integrations: cloneData(currentAccount.integrations),
      seededDemo: currentAccount.seededDemo,
      subscription: cloneData(currentAccount.subscription),
      roundsPlayed: currentAccount.roundsPlayed || 0,
      averageScore: currentAccount.averageScore ?? null,
      bestRound: currentAccount.bestRound ?? null,
      recentFormSummary: currentAccount.recentFormSummary || "First round pending",
    },
    accounts: seeded.accounts,
    accountVault: seeded.accountVault,
    previewAccountId: seeded.previewAccountId,
    auth: {
      status: "signed_out",
      activeUserId: null,
      lastUserId: null,
      provider: null,
      linkedProviders: ["email", "google", "apple"],
      lastIntent: null,
      lastIntentAt: null,
      mode: "login",
      notice: "Sign in with email, create a free golfer account, or use a demo account below for review access.",
      error: "",
    },
    profiles: cloneData(activeWorkspace.profiles),
    rounds: cloneData(activeWorkspace.rounds),
    groups: cloneData(activeWorkspace.groups),
    tournaments: cloneData(activeWorkspace.tournaments),
    gear: cloneData(activeWorkspace.gear),
    social: cloneData(activeWorkspace.social),
    session: {
      activeView: "home",
      previousView: "home",
      transitionDirection: "steady",
      standaloneMode: false,
      installPromptAvailable: false,
      installState: "browser",
      installHintDismissed: false,
      helpSection: "getting-started",
      helpReturnView: "home",
      settingsSection: "account",
      settingsReturnView: "stats",
      activeRoundId: activeWorkspace.userSession.activeRoundId,
      selectedProfileId: activeWorkspace.userSession.selectedProfileId,
      selectedHole: activeWorkspace.userSession.selectedHole,
      summaryRoundId: activeWorkspace.userSession.summaryRoundId,
      lastScoredParticipantId: null,
      lastScoredHole: null,
      lastScorePulseAt: 0,
      feedback: null,
      pendingLabel: "",
      cloudSync: {
        status: "idle",
        scope: "",
        roundId: null,
        userId: null,
        errorMessage: "",
        lastAttemptAt: 0,
        lastSuccessAt: 0,
        retryCount: 0,
      },
      roundSetup: {
        courseQuery: "",
        selectedCourseId: "",
        selectedTeeBoxId: "",
      },
      nearby: createDefaultNearbyState(),
      spotify: createSpotifySessionState(),
    },
  };
}
